### PR TITLE
Add image multiple choice assessment support

### PR DESCRIPTION
**Pull request by tkarabatic**
Adds support for the image variant of the multiple choice assessment.

### CODE REVIEW

**Comment by mbareta** [comment]
@kronicker can someone take a look at this PR?

**Comment by zcuric** [comment]
@kronicker close or merge?

**Comment by kronicker** [comment]
@zcuric For now, neither. This branch supports a branch on Tailor and is published under a specific `ntc` tag.

**Comment by abasic** [comment]
@kronicker Let's close this PR. It is no longer needed.

**Comment by kronicker** [comment]
@ExtensionEngine/tailor Closing due to no further development plans after sync with @ExtensionEngine/ntc-dev.

**Pull request closed without merging**
